USE [ADSS]
GO
IF OBJECT_ID('cfb_Years') IS NOT NULL
	DROP VIEW cfb_Years
GO
CREATE VIEW cfb_Years 
	AS
WITH 
YY AS
	(
	SELECT CAST(DATEPART(YEAR,GETDATE()) AS CHAR(4)) AS YYYY
		  ,CAST(CAST(DATEPART(YEAR,GETDATE()) AS CHAR(4)) + '0701' AS DATETIME) AS MidYear
		  ,1 AS RECURSION
	UNION ALL
	SELECT CAST(DATEPART(YEAR,GETDATE())  - RECURSION AS CHAR(4)) AS YYYY
		,CAST((CAST(DATEPART(YEAR,GETDATE())  - RECURSION AS CHAR(4))) + '0701' AS DATETIME) AS MidYear
		,RECURSION + 1
		FROM YY
	WHERE YYYY > 1992

	)
SELECT *,YYYY AS Years
FROM YY
WHERE YYYY < YEAR(GETDATE())

GO
/********************Test *******************/
SELECT *
FROM cfb_Years
